application:
  name: students

config:
  import: optional:configserver:http://localhost:8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Clevergirl55$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true

# Uncomment the line below if needed
# spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

server:
  port: 8081
